spring:
  datasource:
    password: P@ssword
    url: jdbc:mysql://localhost:3306/todoListDB
    username: todoListUser
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true
    logging:
      level:
        org:
          hibernate:
            type: trace
            dialect: org.hibernate.dialect.H2Dialect
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

logging:
  level:
    org:
      hibernate:
        SQL:
          TRACE
        type:
          descriptor:
            sql:
              BasicBinder:
                TRACE

